In [1]:
import numpy as np
import gymnasium as gym

In [2]:
slippery = False
env = gym.make('FrozenLake-v1', map_name="4x4", is_slippery=slippery, render_mode='human')
env.reset()
for i in range(10):
    env.step(env.action_space.sample())
env.close()

In [3]:
print(env.observation_space)
print(env.action_space)

n_states = env.observation_space.n
n_actions = env.action_space.n

Discrete(16)
Discrete(4)


0: Move left

1: Move down

2: Move right

3: Move up

In [4]:
env = gym.make('FrozenLake-v1', map_name="4x4", is_slippery=slippery)

Q = np.zeros((n_states, n_actions))

print(Q)
num_episodes = 5000
print_idx = [10, 100, 500, 1000, 3000, num_episodes-1]
# 
epsilon = 1
alpha = 0.1
gamma = 0.9
decay_rate = 0.001
eps_max = 1
eps_min = 0.05
for i in range(num_episodes):
    state, _ = env.reset()
    done = False
    total_reward = 0
    while not done:
        if np.random.rand() < epsilon:
            action = env.action_space.sample()
        else:
            action = np.argmax(Q[state])

        state_new, reward, terminated, truncated, _ = env.step(action)    
        done = terminated or truncated
        Q[state, action] = (1-alpha)*Q[state, action] + alpha*(reward + gamma*np.max(Q[state_new]))

        state = state_new
        total_reward += reward
    epsilon = eps_min + (eps_max - eps_min)*np.exp(-decay_rate*i)
    if i in print_idx:
        print('episode ', i, 'total reward', total_reward, 'epsilon', epsilon)
        print(np.round(Q,3))


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
episode  10 total reward 0.0 epsilon 0.9905473420617097
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
episode  100 total reward 0.0 epsilon 0.9095955471341616
[[0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.1 0. ]
 [0.  0.  0.  0. ]]
episode  500 total reward 0.0 epsilon 0.6262041267270018
[[0.4   0.499 0.232 0.378]
 [0.318 0.    0.

In [5]:
env = gym.make('FrozenLake-v1', map_name="4x4", is_slippery=slippery, render_mode='human')

num_episodes = 3

for i in range(num_episodes):
    state, _ = env.reset()
    done = False
    total_reward = 0
    while not done:
        action = np.argmax(Q[state])
        state_new, reward, terminated, truncated, _ = env.step(action)    
        done = terminated or truncated

        state = state_new
        total_reward += reward
    print('episode ', i, 'total reward', total_reward)
env.close()


episode  0 total reward 1.0
episode  1 total reward 1.0
episode  2 total reward 1.0


In [6]:
def index_to_state(row, col):
    return row*4 +col

print(Q[index_to_state(0,0)])

[0.531441  0.59049   0.4782969 0.531441 ]
